services:
  - type: web
    name: tunzy-md-bot
    env: node
    runtime: node
    plan: free
    region: frankfurt
    buildCommand: npm install
    startCommand: node index.js

    envVars:
      NODE_VERSION: 18
      PORT: 3000

    autoDeploy: true
